baseurl: "/site/"
url: http://prabanmfa.com

# Site settings
title: National Martial Arts & Fitness Academy
email: prabanmfa@gmail.com
description: "Learn Karate, Kick Boxking, MMA, Muay Thai, Self-Defence, Fitness Training, Kids Fitness, Yoga, Personal Training, Speed, Strength & Conditioning Training."


# Team names, titles and social links
people:
- name: Praba Karan
  pic: 1
  position: Founder of NMFA
  social:
    - title: facebook
      url: http://facebook.com/karateprabba
    - title: instagram
      url: https://instagram.com/praba8801
    - title: youtube
      url: https://youtu.be/2Nq8FgoS6YY

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://facebook.com/nationalmartialartsandfitness
  - title: instagram
    url: https://www.instagram.com/praba8801
  - title: github
    url: http://github.com/prabanmfa
  - title: youtube
    url: https://youtu.be/2Nq8FgoS6YY

# Postal address (add as many lines as necessary)
address:
  - line: \#58/A9, 2nd Floor,Lakshmi Complex,
  - line: Malleshpalya Main Road,
  - line: Opposite to Vignana Nagar Bus stand,
  - line: Bangalore, Karnataka, India (Pin No 560075)

# Build settings
markdown: kramdown
permalink: pretty
